name: frontend
description: A project management app built with Flutter.
version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  # State management
  provider: ^6.1.1

  # HTTP requests
  http: ^0.13.6

  # Dotenv for environment variables
  flutter_dotenv: ^5.1.0

  # Local storage
  shared_preferences: ^2.2.2

  # Connectivity checking
  connectivity_plus: ^5.0.1

  # Localization
  flutter_localizations:
    sdk: flutter

  # Icons
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - .env
